name: build mern image and push to docker hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-back:
    name: backend
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: build and push docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: subinc/mern_back
        dockerfile: backend/Dockerfile
        tags: latest
  build-and-deploy-front:
    name: frontend
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: build and push docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: subinc/mern_front
        dockerfile: frontend/Dockerfile
        tags: latest    
     


 
